apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-iwjs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-iwjs@sha256:844b24a7a7f45e8e3561904258e9abf4c1fb0f3fb6b6762c1a071490b60d6e1f
        name: my-nodejs
        resources: {}
status: {}
